[package]
name = "cpg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
ratatui = "0.20.1"
regex = "1.7.3"
thiserror = "1.0.40"
tracing = "0.1.37"
tracing-subscriber = "0.3.16"

[profile.release]
debug = true
